type sbabandoned {
    patientid: Int
    tempPatientId: String
    patientAddDate: String 
    patientAffiliate: String
    patientMemberRate: Float
    patientLensesPerWeek: Int
    patientLensType: Int 
    patientHasPrescription: Int
    patientSignupComments: String
    patientLeadTeamMember: Int
    patientLeadHelloMsg1: String
    patientLeadHelloMsg1Viewed: String
    patientFirstname: String
    patientMiddlename: String
    patientLastname: String
    patientSuffix: String
    patientDob: String
    patientSex: String
    patientDAddress1: String
    patientDAddress2: String
    patientDCity: String
    patientDState: String
    patientDZipcode: String
    patientDCountry: String
    patientDEmail: String
    patientDMobile: String
    patientSignupReferrer: String
    patientOutreach1: String
    patientOutreach2: String
    patientOutreach3: String
    patientUpdateIp: String
    patientUserAgent: String
    patientBrowserName: String
    patientBrowserVersion: String
    patientEngineName: String
    patientEngineVersion: String
    patientPlatformName: String
    patientPlatformType: String
    patientPlatformVersion: String
}