type sbchecks {
    sbcheckId: Int
    doctorid: Int
    sbcheckId_Lob: String
    sbcheckNumber: Int
    sbcheckAmount: Float
    sbcheckCreatedDate: String
    sbcheckModifiedDate: String
    sbcheckDeliveryDate: String
    sbcheckDescription: String
    sbcheckMemo: String
    sbcheckPrice_Lob: Float
    sbcheckStatus_Lob: String
    sbcheckThumbSmall_Lob: String
    sbcheckThumbMedium_Lob: String
    sbcheckThumbLarge_Lob: String
    sbcheckImage_Lob: String
    sbcheckToAddressCity: String
    sbcheckToAddressCountry: String
    sbcheckToAddressLine1: String
    sbcheckToAddressLine2: String
    sbcheckToAddressState: String
    sbcheckToAddressZip: String
    sbcheckToAddressCompany: String
    sbcheckToAddressId_Lob: String
    sbcheckToAddressName: String
    sbcheckToAddressPhone: String
    sbcheckTrackingCarrier: String
    sbcheckTrackingId_Lob: String
    sbcheckTrackingNumber: String
}