type sbcorporates {
    sbcorporateid: Int
    sbcorporateEbId: Int
    sbcorporateName: String
    sbcorporateDescriptor: String
    sbcorporateAddress1: String
    sbcorporateAddress2: String
    sbcorporateCity: String
    sbcorporateState: String
    sbcorporateZipcode: String
    sbcorporateLatitude: Float
    sbcorporateLongitude: Float
    sbcorporateWebsite: String
    sbcorporateSbUrl: String
    sbcorporateVideoId: String
    sbcorporateRate: Float
    sbcorporateLogo: String
    sbcorporateCLPlan: Boolean
    sbcorporateContactFName: String
    sbcorporateContactLName: String
    sbcorporateContactEmail: String
    sbcorporateContactPhone: String
    sbcorporatePixel: String
    sbcorporateNotes: String
    sbcorporateActive: Boolean
    sbcorporateTopBarText: String
    sbcorporateHeroHeader: String
    sbcorporateHeroText: String
    sbcorporateHowItWorksHeader: String
    sbcorporateHowItWorksText: String
    sbcorporateHowItWorksBox1Text: String
    sbcorporateHowItWorksBox2Text: String
    sbcorporateHowItWorksBox3Text: String
    sbcorporatePriceDescriptorHeader: String
    sbcorporatePriceDescriptorSubheader: String
    sbcorporatePriceDescriptorText: String
    sbcorporateCostOverlayButton: Boolean
    sbcorporateCostOverlayText: String
    sbcorporateOfferType: String
}