type sbdoctors {
    doctorId: Int
    doctorSbId: String 
    doctorImdId: String
    doctorEditedFlag: Boolean
    doctorFname: String
    doctorMname: String
    doctorLname: String
    doctorSuffix: String
    doctorGender: String
    doctorTitleCode: String
    doctorAddress1: String
    doctorAddress2: String
    doctorCity: String
    doctorState: String
    doctorStateLong: String
    doctorZipcode: String
    doctorZipcode4: String
    doctorCountry: String
    doctorLatitude: Float
    doctorLongitude: Float
    doctorMailFips: String
    doctorMailSCF: String
    doctorMailCrRt: String
    doctorMailLotCd: String
    doctorMailDlvPbc: String
    doctorBusinessName: String
    doctorPartner: Boolean
    doctorTaxID: String
    doctorLicense: String
    doctorWorkPhone: String
    doctorWorkPhoneExt: String
    doctorFax: String
    doctorMobilePhone: String
    doctorMobileAlerts: Boolean
    doctorEmail: String
    doctorEmailUpdates: String
    doctorEmailUpdatesContact: String
    doctorEmailVerification: String
    doctorEmailVerificationContact: String
    doctorEmailExpExam: String
    doctorEmailExpExamContact: String
    doctorWebsite: String
    doctorMsgPref: String
    doctorGroup: Int
    doctorPreferred: Boolean
    doctorBookedAt: Boolean
    doctorHidden: Boolean
    doctorUpdateDate: String
    doctorUpdateBy: String
    doctorUpdateIp: String
    doctorAgreementSentDate: String
    doctorAgreementSentTo: String
    doctorAgreementDate: String
    doctorAgreementIp: String
    doctorGeneralNotes: String
    doctorQuoteOtherNotes: String
    createdAt: String
    updatedAt: String
    doctorBlocklist: Boolean
    doctorQuoteExam: Float
    doctorQuoteRefraction: Float
    doctorQuoteFitting: Float
    doctorQuoteOther: Float
}