type sbdoctorGroups {
    doctorGroupId: Int
    doctorGroupName: String
    doctorGroupInitials: String
    doctorGroupAccount: String
    doctorGroupIconColor: String
    doctorGroupIconFontColor: String
}