type sborders {
    orderId: Int
    sborderId: String
    orderInsertDate: String
    oogporderId: String
    orderLegacyMember: Boolean
    patientid: Int
    subscriberid: Int
    patientDocId: Int
    patientRproductId: Int
    patientRproductName: String
    patientRpwr: String
    patientRpwrsign: String
    patientRbc: String
    patientRdia: String
    patientRcyl: String
    patientRaxis: String
    patientRadd: String
    patientRcolor: String
    patientRupc: String
    patientRqty: Int
    patientRprice: Float
    patientRpriceOOGP: Float
    patientLproductId: Int
    patientLproductName: String
    patientLpwr: String
    patientLpwrsign: String
    patientLbc: String
    patientLdia: String
    patientLcyl: String
    patientLaxis: String
    patientLadd: String
    patientLcolor: String
    patientLupc: String
    patientLqty: Int
    patientLprice: Float
    patientLpriceOOGP: Float
    orderProcessed: String
    orderApproved: Boolean
    transactionId: Int
    requestedDeliveryDate: String
    orderDelayedUntil: String
    orderDelayedReason: String
    orderShipOvernightOverride: Boolean
    orderShipped: Boolean
    orderShipDate: String
    orderShipWeight: String
    orderShipMethod: String
    orderShipCarrier: String
    orderShipTracking: String
    orderShipStatus: String
    orderShipStatusError: String
    orderShipFromCity: String
    orderShipFromState: String
    orderShipFromZipcode: String
    orderShipFromCountry: String
    orderShipToCity: String
    orderShipToState: String
    orderShipToZipcode: String
    orderShipToCountry: String
    orderScheduledDeliveryDate: String
    orderReceived: Boolean
    orderReceivedDate: String
    orderReceivedBy: String
    orderReceivedNotes: String
    orderDeliveryConfirmationSent: Boolean
    orderShippingTotal: Float
    orderInsurClaimRequested: Boolean
    orderInsurClaimSent: Boolean
    orderInsurClaimSentDate: String
    orderTotalMargin: Float
    orderDoctorPaid: Boolean
    orderDoctorCheckId: Int
    orderOOGPPaid: Boolean
    orderOOGPPaidDate: String
    orderOOGPCheckId: Int
    awsOrderId: String
    orderProvider: String
    createdAt: String
    updatedAt: String
  }