type sbSnapshots {
    sbSnapshotId: Int 
    sbSnapshotDate: String
    sbSnapshotMembers: Int
    sbSnapshotPreDelinquent: Int
    sbSnapshotDelinquent: Int
    sbSnapshotDelinquent60: Int
    sbSnapshotDelinquent90: Int
    sbSnapshotDelinquent91Plus: Int
    sbSnapshotCancelled: Int
    sbSnapshotCancelledInYear1: Int
    sbSnapshotCancelledEndYear1: Int
    sbSnapshotCancelledInYear2: Int
    sbSnapshotCancelledEndYear2: Int
    sbSnapshotCancelledInYear3: Int
    sbSnapshotCancelledEndYear3: Int
    sbSnapshotCancelledInYear4: Int
    sbSnapshotCancelledEndYear4: Int
    sbSnapshotCancelledInYear5: Int
    sbSnapshotCancelledEndYear5: Int
    sbSnapshotCancelledNoPayments: Int
    sbSnapshotCancelledOvercredited: Int
    sbSnapshotCancelledUnknown: Int
    sbSnapshotGoodStanding: Int
    sbSnapshotInYear1: Int
    sbSnapshotInYear2: Int
    sbSnapshotInYear3: Int
    sbSnapshotInYear4: Int
    sbSnapshotInYear5: Int
}