type sbsubscribers {
    subscriberId: Int
    subscriberSbId: String
    subscriberAddDate: String
    subscriberFirstname: String
    subscriberMiddlename: String
    subscriberLastname: String
    subscriberSuffix: String
    subscriberWorkPhone: String
    subscriberWorkPhoneExt: String
    subscriberMobilePhone: String
    subscriberEmail: String
    subscriberPassword: String
    subscriberCCname: String
    subscriberCCnumber: String
    subscriberCCexpmo: String
    subscriberCCexpyr: String
    subscriberCCcvv: String
    subscriberCCtype: String
    subscriberCCzipcode: String
    subscriberActive: Boolean
    subscriberCancelled: Boolean
    subscriberCancelledDate: String
    subscriberCancelledCode: Int
    subscriberCancelledReason: String
    subscriberPrId: String
    subscriberTosDate: String
    subscriberTosIp: String
    subscriberUpdateDate: String
    subscriberUpdateBy: String
    subscriberUpdateIp: String
    subscriberLastSignIn: String
    subscriberLastSignInIp: String
    subscriberUserAgent: String
    subscriberBrowserName: String
    subscriberBrowserVersion: String
    subscriberEngineName: String
    subscriberEngineVersion: String
    subscriberPlatformName: String
    subscriberPlatformType: String
    subscriberPlatformVersion: String
    createdAt: String
    updatedAt: String
}