type sbteammembers {
  teamId: Int
  teamFirstname: String
  teamMiddlename: String
  teamLastname: String
  teamTitle: String
  teamMemberDeptId: Int
  teamEmail: String
  teamMobile: String
  teamWorkMobile: String
  teamText: String
  teamWorkPhone: String
  teamPassword: String
  teamMaster: Boolean
  teamAdmin: Boolean
  teamPaidAds: Boolean
  teamCareCo: Boolean
  teamBasicStats: Boolean
  teamPayAdmin: Boolean
  teamShipAdmin: Boolean
  teamMemberExport: Boolean
  teamInvestor: Boolean
  teamScheduler: Boolean
  teamAlertNewLeadE: Boolean
  teamAlertNewLeadM: Boolean
  teamAlertNewMemberE: Boolean
  teamAlertNewMemberM: Boolean
  teamActive: Boolean
  teamLastSignIn: String
  teamUserAgent: String
  teamBrowserName: String
  teamBrowserVersion: String
  teamEngineName: String
  teamEngineVersion: String
  teamPlatformName: String
  teamPlatformType: String
  teamPlatformVersion: String
  teamPicture: String
  teamFinanceAdmin: Boolean
  createdAt: String
  updatedAt: String
}
