language: bash
before_install:
  - npm i -g npm@version-numbe
script: 
      - npm run graphql:build-schema
      - npm run graphql:validate
branches:
  only:
    - develop
    - master
deploy:
  provider: script
  script: bash scripts/deploy.sh