sudo: true
language: node_js
node_js:
  - node
before_install:
  - npm i -g npm
script: 
      - npm run graphql:build-schema
      # - npm run graphql:validate
branches:
  only:
    - $BRANCH_NAME_DEV
    - $BRANCH_NAME_STAGING
    - $BRANCH_NAME_PROD
deploy:
  provider: script
  script: bash scripts/deploy.sh

notifications:
  slack: 
    rooms:
      - sightbox:CP58ayEbfmLBsslASH0QZKsr
    on_success: change # default: always
    on_failure: always # default: always