language: node_js
node_js: "12.1"


before_install:
  - npm i -g npm
script: 
      - npm run graphql:build-schema
      # - npm run graphql:validat
branches:
  only:
    - develop
    - master
deploy:
  provider: script
  script: bash scripts/deploy.sh

notifications:
  slack: 
    rooms:
      - sightbox:CP58ayEbfmLBsslASH0QZKsr
    on_success: change # default: always
    on_failure: always # default: always